attend:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: holdsport
    activity_id:
      required: true
      example: 52272675
      selector:
        text:

decline:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: holdsport
    activity_id:
      required: true
      example: 52272675
      selector:
        text:
